# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
            name: Remove whitespace from the end of lines
          - id: end-of-file-fixer
            name: Ensure that files end with a newline
          - id: check-yaml
            name: Ensure yaml files can be parsed
          - id: check-added-large-files
            name: Ensure no large files have been committed
          - id: check-ast
            name: Ensure that python files can be parsed
          - id: check-case-conflict
            name: Ensure there are no file name conflicts on case-insensitive filesystems
          - id: check-merge-conflict
            name: Ensure no merge conflict markers are committed

    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            name: Format code in python files using black

    - repo: https://github.com/pycqa/isort
      rev: 5.10.0
      hooks:
          - id: isort
            name: Sort imports in python files with isort
